[FEATURE] Add support for iNavigateTo
SAP/openui5-generic-app-testing pull request #3
Opened 2018-02-08 12:34 UTC by gembeconsulting

This PR provides support for iNavigateTo step, that sets a new hash to the app under test to trigger navigation. Developers can create test scenarios for navigation and routing of their UI5 app.

PR contains test scenario "iNavigateTo changes Hash" to verify step behavior.

2018-02-11 09:37 UTC, darksmo requested changes
Well done. Let's fix some points and then merge this!

2018-02-11 09:37 UTC, darksmo commented on src/steps/iNavigateTo.js
> +        description: "Performs navigation using hash.",
- Do not include "." for consistency. 
- Also I would say "Navigates within the application using inner-app route". We may extends with Fiori Launchpad intent-based navigation later.

2018-02-11 09:37 UTC, darksmo commented on src/steps/iNavigateTo.js
> +        synopsis: "I navigate to <hash>",
- Use 'I navigate to ROUTE'  (see synopsis in all other actions. Parameters are capitalized, with square brackets if they are optional)

2018-02-11 09:37 UTC, darksmo commented on src/steps/iNavigateTo.js
> +            "I navigate to /Customers/4711?&tab=person"
- Consider adding more examples, especially with multiple parameters. You can test the examples without additional code via `npm test`, and see if they match the regex.
- In ...4711?&tab=person, was the "&" on purpose? I thought example should come without & although there are URLs with ?& around...
- Also perhaps we should add more example with multiple parameters

2018-02-11 09:37 UTC, darksmo commented on src/steps/iNavigateTo.js
> +        "([=a-zA-Z0-9\/\?\&]+){1}",   //hash with parameters
Would use a more expressive regex here: `"(/|((/[a-zA-Z0-9_]+)+([?]([&a-zA-Z0-9_]+?=[^&?]*?)+)?))"` . You don't need to escape all characters when using a character class see https://www.regular-expressions.info/refcharclass.html .

2018-02-11 09:37 UTC, darksmo commented on src/steps/iNavigateTo.js
> +        oHasherChanger = sap.ui.test.Opa5.getHashChanger();
- Avoid global. Use this.Opa5.getHashChanger() instead

2018-02-11 09:38 UTC, darksmo commented
Also let's not forget to sign CLA - otherwise we can't merge.

2020-08-05 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/openui5-generic-app-testing?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/openui5-generic-app-testing?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/openui5-generic-app-testing?pullRequest=3) it.</sub>

2021-05-25 09:15 UTC, SebastianWolf-SAP commented
This repository is no longer maintained and will be archived. Therefore we will close this pull request. 

Thank you for your understanding and best regards, 

Sebastian (SAP Open Source Program Office)

2021-05-25 09:15 UTC, closed without merging